### ISSUE TITLE
mapc2p geo not properly passed to MB GK app

### ISSUE THREAD

**Issue by manauref** [ammarhakim/gkylzero#521] opened 2024-11-11 02:58 UTC
The contents of the geometry struct don't appear to be passed properly to the MB app, we noticed this while setting up a mapc2p MB sim.

I think we need to create a tmp input struct and use a memcpy the way we do for the field inputs: https://github.com/ammarhakim/gkylzero/blob/846bcdfb54e00e2e10f0c8d9f1bf03588ef8f229/apps/gyrokinetic_multib.c#L333-L386

**Comment by akashukla** [comment] 2024-11-12 21:31
It turns out this is not an issue in the coed in `apps/`. It is an input file issue and has been resolved in commit 47910d224d4caa992fecf36f623232ca96db7dc6 which shows an example of how to properly initialize mapc2p MB geometry in the `rt_multib_slab_2x2v_p1` regression test.

**Closed by akashukla** 2024-11-12 21:31 UTC
Labels: bug
